{% set name = "grimp" %}
{% set version = "3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grimp-{{ version }}.tar.gz
  sha256: 5ec7e7475a3616b1bec14d852784fa2e3829a4331fd2309a055f1e75ba5a4f50

build:
  skip: true  # [py<38]
  script:
    #- cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    #- {{ compiler('c') }}
    - {{ compiler('rust') }}
    #- cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - typing_extensions >=3.10.0.0

test:
  imports:
    - grimp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/grimp/
  summary: Builds a queryable graph of the imports within one or more Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
