{% set name = "grimp" %}
{% set version = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grimp-{{ version }}.tar.gz
  sha256: 20d2acb8a07504df17abd31f6d312996121014331a1072bac923162efec28b77

build:
  skip: true  # [py<38]
  script:
    #- cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
    #- {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    #- cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - typing-extensions >=3.10.0.0

test:
  imports:
    - grimp
  commands:
    - pip check
    - python -c "from grimp import build_graph"
  requires:
    - pip

about:
  home: https://pypi.org/project/grimp/
  summary: Builds a queryable graph of the imports within one or more Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - peterbygrave
    - rxm7706
