{% set name = "grimp" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grimp-{{ version }}.tar.gz
  sha256: 5b1a541b3e67301f00af618c850039eb1b93d9ae82d049e9ce77e0867e38a7eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - typing_extensions >=3.10.0.0
#   - networkx >=2.1,<3

test:
  imports:
    - grimp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/grimp/
  summary: Builds a queryable graph of the imports within one or more Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
