# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: grimp
  version: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/grimp-${{ version }}.tar.gz
  sha256: 920d069a6c591b830d661e0f7e78743d276e05df1072dc139fc2ee314a5e723d

build:
  number: 1
  script:
    - if: unix
      then:
        # Unix recipe
        - export OPENSSL_DIR="$PREFIX"
      else:
        # Win recipe  # work around long path problem,
        # hack: path too long for pixi_config subpackage, https://github.com/prefix-dev/pixi/issues/3691
        - set CARGO_HOME=C:\.cargo
        - md %CARGO_HOME%
        - if errorlevel 1 exit 1
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python
    - joblib >=1.3.0
    - typing_extensions >=3.10.0.0

tests:
  - python:
      imports:
        - grimp
      pip_check: true
  - script:
      - "python -c \"from grimp import build_graph\""

about:
  summary: Builds a queryable graph of the imports within one or more Python packages.
  license: BSD-2-Clause
  license_file:
    - LICENSE
  homepage: https://pypi.org/project/grimp/
  description: |
    Builds a queryable graph of the imports within one or more Python packages.
  repository: https://pypi.org/project/grimp/

extra:
  recipe-maintainers:
    - cshaley
    - peterbygrave
    - rxm7706
