# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: grimp
  version: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/grimp-${{ version }}.tar.gz
  sha256: b677ac17301d7e0f1e19cc7057731bd7956a2121181eb5057e51efb44301fb0a

build:
  number: 0
  script:
    - if: osx
      then:
        - if [[ "${MACOSX_SDK_VERSION}" != "11.0" ]]; then exit 1; fi
    - if: unix
      then:
        # Unix recipe
        - export OPENSSL_DIR="$PREFIX"
        - cargo install --locked --bin rattler-build --root ${PREFIX} --path . --no-track
        - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      else:
        # Win recipe
        # hack: path too long for pixi_config subpackage, https://github.com/prefix-dev/pixi/issues/3691
        - set CARGO_HOME=C:\.cargo
        - md %CARGO_HOME%
        - cargo install --locked --bins --root %PREFIX% --path . --no-track
        - if errorlevel 1 exit 1
        - cargo-bundle-licenses --format yaml --output %SRC_DIR%/THIRDPARTY.yml
        - if errorlevel 1 exit 1

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1,<2

    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python
    - joblib >=1.3.0
    - typing_extensions >=3.10.0.0

tests:
  - python:
      imports:
        - grimp
      pip_check: true
  - script:
      - "python -c \"from grimp import build_graph\""

about:
  summary: Builds a queryable graph of the imports within one or more Python packages.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/grimp/
  description: |
    Builds a queryable graph of the imports within one or more Python packages.
  repository: https://pypi.org/project/grimp/

extra:
  recipe-maintainers:
    - cshaley
    - peterbygrave
    - rxm7706
